### ISSUE TITLE
HELM proxy with relative path in index.yaml throws 404 Not Found issue

### ISSUE THREAD

**Issue by au-hao** [sonatype-nexus-community/nexus-repository-helm#20]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I am trying to use helm proxy and understood there are some similar questions posted but I still cannot figure out how to use it properly. Need a help.

* **What feature or behavior is this required for?**
Issue:
```bash
...Successfully got an update from the "helm-proxy" chart repository
...Successfully got an update from the "au-jfrog-helm" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading base from repo http://localhost:8081/repository/jfrog-proxy/
Save error occurred:  could not download http://localhost:8081/repository/jfrog-proxy/autonomic/helm/base-0.0.1-alpha.84.tgz: Failed to fetch http://localhost:8081/repository/jfrog-proxy/autonomic/helm/base-0.0.1-alpha.84.tgz : 404 Not Found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download http://localhost:8081/repository/jfrog-proxy/autonomic/helm/base-0.0.1-alpha.84.tgz: Failed to fetch http://localhost:8081/repository/jfrog-proxy/autonomic/helm/base-0.0.1-alpha.84.tgz : 404 Not Found
```

proxy setup:
![image](https://user-images.githubusercontent.com/40636256/47570505-5c833780-d904-11e8-9d2e-49dab459d40f.png)

```bash
helm repo list:
NAME                 URL
helm-proxy   	http://localhost:8081/repository/jfrog-proxy/
```
index.yaml
```yaml
apiVersion: v1
entries:
  base:
  - apiVersion: v1
    created: 2018-10-25T19:56:58.589Z
    description: A base Helm chart for Autonomic general use
    digest: 3554b5981ca4eb4f41ca1b00585be8518a83afeb962c418588aaf7c324174d61
    name: base
    urls:
    - autonomic/helm/base-0.0.1-alpha.84.tgz
    version: 0.0.1-alpha.84
```
requirements.yaml
```yaml
dependencies:
  - name: base
    version: "^0.0.x-alpha.x"
     repository: http://localhost:8081/repository/jfrog-proxy/
```
* **How could we solve this issue? (Not knowing is okay!)**
N/A
* **Anything else?**
N/A
