### ISSUE TITLE
urls field generation hardcoded in index.yaml

### ISSUE THREAD

**Issue by verhyppo** [sonatype-nexus-community/nexus-repository-helm#94]
When retrieving the `index.yaml` from hosted or proxy repositories, `urls` for entries contains only the artifact name.
The actual behaviuor should be similar to:
```
entries:
  <name>:
  - apiVersion: v1
    appVersion: <app-version>
    [OMITTED FOR BREVITY] 
    urls:
    - https://<host and path for chart repository>/<name>-<version>.tgz
    version: <version>
```
this result on [helm charts repository](https://helm.sh/) is usually achieved using the following command:
`helm repo index <local-repo-folder>  --url https://<host and path for chart repository>/`
This way, the index is generated prepending `--url` value to all charts in the `urls ` field of the `index.yaml`

* **What are you trying to do?**
I'm using helm plugin as hosted repository on one nexus instance. 
I also would like to download charts using http, first retrieving the `index.yaml` and then use (one of) the urls field to download the `tar.gz` file. 

* **What feature or behavior is this required for?**
In order to retrieve the full url to download the chart via http

* **How could we solve this issue? (Not knowing is okay!)**

It seems that url are generated statically by `org.sonatype.repository.helm.internal.createindex.CreateIndexServiceImpl#createListOfRelativeUrls` that does not take host url. 
Also, it seems that there is no host configuration in the administration panel to allow also the use of proxy pass.

* **Anything else?**
